---
connection_options:
  napalm:
    platform: ios
    extras:
      optional_args:
        timeout: 90
        global_delay_factor: 2
  netmiko:
    extras:
      conn_timeout: 90
  paramiko:
    extras:
    conn_timeout: 90
