---
CORE:
  hosts:
    R1:
  username: vagrant
  password: vagrant
  platform: ios
  data: core
DIST:
  hosts:
    D1:
    D2:
  username: vagrant
  password: vagrant
  platform: ios
  data: dist
ACCESS:
  hosts:
    S1:
    S2:
  username: admin
  password: admin
  platform: ios
  data: access
  connection_options:
    napalm:
      platform: ios
      extras:
        optional_args:
          dest_file_system: "unix:"
          inline_transfer: true
